version: '3.3'
services:
  mysql:
    image: mysql:5
    environment:
    - MYSQL_DATABASE=my_store
    - MYSQL_USER=root
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_HOST=mysql
    - MYSQL_ROOT_PASSWORD=admin123
    ports:
    - 8080:80
